### ISSUE TITLE
proxy > traefik as entry point

### ISSUE THREAD

**Issue by stkac** [jsimonetti/docker-gns3-server#1]
Hi, do you know how to run your container through a proxy, in my case traefik. **I get Configuration error - 'network_mode' and 'networks' cannot be combined"**

Here my docker-compose.yml

```
networks:
  traefik-00:
    name: traefik-00
    external: true

services:
  gns3-server:
    container_name: gns3-server
    hostname: gns3.domain.tld
    image: jsimonetti/gns3-server:latest 
    privileged: true
    restart: always
    environment:
      - BRIDGE_ADDRESS="172.21.1.1/24"
    labels:
      - traefik.enable=true
      - traefik.backend=gns3.domain.tld
      - traefik.frontend.rule=Host:gns3.domain.tld
      - traefik.docker.network=traefik-00
    network_mode: "host"
    networks:
      - traefik-00
    expose:
      - "3080"
    volumes:
      - ./data:/data
```

Thanks in advance,
