### ISSUE TITLE
virbr0 interface won't get address from BRIDGE_ADDRESS variable

### ISSUE THREAD

**Issue by Azertooth** [jsimonetti/docker-gns3-server#16]
as title, when I sh into the container i can't see the specified variable address assigned to the virtual bridge

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: virbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether 16:da:f3:d4:be:ea brd ff:ff:ff:ff:ff:ff
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:4e:0b:21:d3 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
1997: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:0a:4c:59:5b brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.1/24 brd 10.76.89.127 scope global eth0
       valid_lft forever preferred_lft forever
```

docker-compose configuration

```
  gns3:
    privileged: true
    container_name: gns3
    hostname: gns3
    image: jsimonetti/gns3-server:latest
    network_mode: host
    ports:
      - 8080:80
    environment:
      - BRIDGE_ADDRESS="172.23.89.1/24"
    volumes:
      - ./gns3:/data
    restart: unless-stopped
```
