### ISSUE TITLE
Cannot Access SSH via docker network bridge

### ISSUE THREAD

**Issue by JustinGrote** [jsimonetti/docker-gns3-server#204]
First off thank you for this excellent container!

I have this docker compose config for a devcontainer:
```
version: '3.8'

services:
  ansible:
    image: ghcr.io/ansible/community-ansible-dev-tools:latest
    user: root
    privileged: true

    # Keep devcontainer running for attach
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:gns3
    volumes:
      #Devcontainer entry point
      - ..:/workspace:cached

  gns3:
    image: jsimonetti/gns3-server:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - gns3-data:/data


volumes:
  gns3-data:
```

For testing purposes I don't have my ansible container sharing the network interface of the gns3, so it sits on the same network (it gets 10.89.0.2 and gns3 gets 10.89.0.3)

In GNS3 I have this topology:

![Image](https://github.com/user-attachments/assets/172e4fb7-ef28-4742-9899-32960fcaf492)

I bridge to eth0 on the gns3 container and give my Cisco 1000v switch an IP of 10.89.0.10. I can ping it and http to it however ssh and telnet don't work, debug IP packet on the switch shows the packet arrive and then do...nothing. This happens both from the gns3 machine and from the ansible machine.

If I create another switch and direct attach it on another port, giving them IP's 1.1.1.1 and 1.1.1.2 respectively, it works fine. If I do this outside of docker, it works fine.

If I instead attach the switch to `virbr0`, enable DHCP so it gets an address from dnsmasq, SSH from the GNS3 machine works fine.

enable forwarding on eth0 and virbr0 in the gns3 container, and then set up an IPtables nat from port 3001 to 172.21.1.5, that also works fine. This is a sufficient workaround for my use case (testing ansible against a switch)

No console messages on the 1000v that indicate it is dropping the packets.

Any idea what would be different from bridging to eth0 vs bridging to virbr0 that would cause this problem? It's super weird that ping/http work fine from ansible container to the switch, but telnet/ssh don't (and I verified they are enabled and the packets are arriving both via packet trace and via debug ip packet)
