### ISSUE TITLE
Unable to load container

### ISSUE THREAD

**Issue by vk6xebec** [jsimonetti/docker-gns3-server#63]
Hello, 

I am unable to load the gn3 container by using docker on a remote machine. When I try to launch the server web page, I get nothing "site can't be reached" error on the browser. eg http://192.168.3.50:3030 - nothing opens up.

Expected response: should be able to open up GNS3 on a remote site using a custom port (3080 or any other)

This is my docker compose file:

```
services:
    gns3-server:
      image: jsimonetti/gns3-server:latest
      container_name: gns3
      privileged: false
      environment:
      - BRIDGE_ADDRESS=172.21.1.1/24
      volumes:
       - ./data:/data
      network_mode: host
```
-------------------------------
Log file attached
[gns3logs.txt](https://github.com/jsimonetti/docker-gns3-server/files/9474583/gns3logs.txt)
From the logs, it looks like this is the culprit:
```
brctl: bridge virbr0: Operation not permitted
ip: ioctl 0x8913 failed: No such device
ip: can't find device 'virbr0'
getsockopt failed strangely: Operation not permitted
```

-------------------------------

OS VM details:
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

-------------------------------
Docker version 20.10.17, build 100c701
Docker Compose version v2.6.0
